#include "../fattn-vec.cuh"
DECL_FATTN_VEC_CASE( 64, GGML_TYPE_RQ3_ISO, GGML_TYPE_RQ3_ISO);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_RQ3_ISO, GGML_TYPE_RQ3_ISO);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_RQ3_ISO, GGML_TYPE_RQ3_ISO);
DECL_FATTN_VEC_CASE(512, GGML_TYPE_RQ3_ISO, GGML_TYPE_RQ3_ISO);
